---
language: php

os: linux
dist: focal

version: ~> 1.0

php: "7.4"

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.rvm"
    - "${TMPDIR:-/tmp}/phpstan/cache"

services:
  - mysql

env:
  global:
    - ORCA_SUT_NAME=drupal/acquia_search
    - ORCA_SUT_BRANCH=3.1.x
    - ORCA_VERSION=^3
    - ORCA_PACKAGES_CONFIG_ALTER=../acquia_search/tests/packages_alter.yml
    - ORCA_TELEMETRY_ENABLE=TRUE

matrix:
  fast_finish: true
  include:
    - { env: ORCA_JOB=STATIC_CODE_ANALYSIS, name: "Static code analysis" }
    - { env: ORCA_JOB=LOOSE_DEPRECATED_CODE_SCAN, name: "Loose deprecated code scan" }
    - { env: ORCA_JOB=STRICT_DEPRECATED_CODE_SCAN, name: "Strict deprecated code scan" }
    - { env: ORCA_JOB=ISOLATED_TEST_ON_CURRENT, name: "Isolated test w/ recommended package versions" }
    - { env: ORCA_JOB=INTEGRATED_TEST_ON_CURRENT, name: "Integrated test w/ recommended package versions" }
    - { env: ORCA_JOB=INTEGRATED_TEST_ON_PREVIOUS_MINOR, name: "Integrated test w/ recommended package versions & previous minor release of Drupal core" }
    - { env: ORCA_JOB=ISOLATED_TEST_ON_CURRENT_DEV, name: "Isolated test w/ dev package versions" }
    - { env: ORCA_JOB=INTEGRATED_TEST_ON_CURRENT_DEV, name: "Integrated test w/ dev package versions" }
    - { env: ORCA_JOB=INTEGRATED_TEST_ON_NEXT_MINOR, name: "Integrated test w/ package versions & next minor version of Drupal core" }
    - { env: ORCA_JOB=INTEGRATED_TEST_ON_NEXT_MINOR_DEV, name: "Integrated test w/ dev package versions & next minor dev version of Drupal core" }
    - { env: ORCA_JOB=ISOLATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_BETA_OR_LATER, php: "8.1", name: "Isolated test on next major, latest minor beta-or-later Drupal core version" }
    - { env: ORCA_JOB=INTEGRATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_BETA_OR_LATER, php: "8.1", name: "Integrated test on next major, latest minor beta-or-later Drupal core version" }
    - { env: ORCA_JOB=ISOLATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_DEV, php: "8.1",  name: "Isolated test on next major, latest minor dev Drupal core version" }
    - { env: ORCA_JOB=INTEGRATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_DEV, php: "8.1", name: "Integrated test on next major, latest minor dev Drupal core version" }
  allow_failures:
    - env: ORCA_JOB=LOOSE_DEPRECATED_CODE_SCAN
    - env: ORCA_JOB=ISOLATED_TEST_ON_CURRENT_DEV
    - env: ORCA_JOB=INTEGRATED_TEST_ON_CURRENT_DEV
    - env: ORCA_JOB=INTEGRATED_TEST_ON_NEXT_MINOR
    - env: ORCA_JOB=INTEGRATED_TEST_ON_NEXT_MINOR_DEV
    - { env: ORCA_JOB=ISOLATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_DEV, php: "8.1"}
    - { env: ORCA_JOB=INTEGRATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_DEV, php: "8.1"}
    - { env: ORCA_JOB=ISOLATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_BETA_OR_LATER, php: "8.1"}
    - { env: ORCA_JOB=INTEGRATED_TEST_ON_NEXT_MAJOR_LATEST_MINOR_BETA_OR_LATER, php: "8.1"}

before_install:
  - composer create-project --no-dev acquia/orca ../orca "$ORCA_VERSION"
  - ../orca/bin/travis/before_install.sh

install: ../orca/bin/travis/install.sh

before_script: ../orca/bin/travis/before_script.sh

script: ../orca/bin/travis/script.sh

before_cache: ../orca/bin/travis/before_cache.sh

after_success: ../orca/bin/travis/after_success.sh

after_failure: ../orca/bin/travis/after_failure.sh

after_script: ../orca/bin/travis/after_script.sh
